### ISSUE TITLE
The program has a memory leak, and the memory has been growing while running, growing to more than 100 GB

### ISSUE THREAD

**Issue by wzharies** [CGCL-codes/mioDB#16]
I only modified the path and nvm_node

**Comment by Gumi-presentation-by-Dzh** [comment]
This comes from MioDB's elastic buffer and zero-copy design. zero-copy does not release memory in the first place, we only release memory by lazy-copy when the PMTable is flushed from the elastic buffer into the storage area. The related design can be seen in our paper. We use NVM as memory (this may be a case where you find too much memory usage, please do not define NVM node directly without NVM memory extension, this will cause OOM), during the program run, data writing or modification will cause LSM to increase PMTable, this will be elastic to use NVM for buffering. When the load or modification is smooth, the temporarily used NVM will be released and the KV system smoothes out.

Overall, this is not a potential problem, but a phenomenon based on MioDB's optimization strategy.

**Comment by QingyangZ** [comment]
How to use NVM as memory? Does that make data persistent?

**Comment by Gumi-presentation-by-Dzh** [comment]
@QingyangZ This is a very critical issue. The essential purpose of our work is to explore how NVM, as part of memory scaling, can be combined with LSM. So the first step requires memory scalability of NVM. 

You can check my earlier discussion on the issue with the Intel NVM driver (impctl) open source code [(this way)](https://github.com/intel/ipmctl/issues/120). The link to the Intel bigwig sscargal's answer is now defunct, so I had to go through looking up the relevant link on the Intel website [(this way)](https://www.intel.cn/content/www/cn/zh/developer/articles/technical/volatile-use-of-persistent-memory.html). Although there are differences between this approach and the way we implemented it, there is not much difference in essence. 

In our scenario, we only discuss the cache design of NVM as a memory extension, and we flush out the additional overhead of programming with PMDK for all comparison systems. We also have a version of the code that implements memory allocation based on the PMDK, but the version we publish now is based on the NVM memory extension.
