### ISSUE TITLE
serialization & deserialization time  

### ISSUE THREAD

**Issue by ErosBryant** [CGCL-codes/mioDB#17]
Where is the code for measuring serialization & deserialization time in LEVELDB code ?
I can't found it

**Comment by Gumi-presentation-by-Dzh** [comment]
LevelDB itself does not provide the interface for these two tests, we only open source the test interface provided by MioDB. If you need LevelDB's own test interface, you can implement it yourself, which requires code modification.

**Comment by ErosBryant** [comment]
Sorry.I explained it wrong.
I wanted to ask where you measured the code in MIODB.

**Comment by Gumi-presentation-by-Dzh** [comment]
Please read our test script in detail and check our statistics file and the corresponding statistics generation section against it. /mioDB/test_sh/parser.sh

**Comment by Gumi-presentation-by-Dzh** [comment]
For other systems, there is no self-contained test interface and calls, so we have no choice but to make coupling changes in the code, so we cannot open source (because we need to open source the entire system code), so we only open source the system test interface and test scripts for MioDB.
