### ISSUE TITLE
Not cleared the warning here. Assign ? or Equals ?

### ISSUE THREAD

**Issue by KINGFIOX** [CGCL-codes/mioDB#18]
https://github.com/CGCL-codes/mioDB/blob/master/db/skiplist.h#L729

**Comment by Gumi-presentation-by-Dzh** [comment]
Thanks for your question. This is indeed a bug that may affect the removal of redundant nodes during the merge process, thus degrading system performance. Fortunately, it does not affect the system correctness, otherwise the query will be wrong. May be you can change it to equal and try again.
